name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Build and Test (macOS)
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install SwiftLint
        run: |
          curl -L https://github.com/realm/SwiftLint/releases/download/0.63.2/SwiftLint.pkg -o SwiftLint.pkg
          sudo installer -pkg SwiftLint.pkg -target /

      - name: Run SwiftLint
        run: swiftlint lint --reporter github

      - name: Build package
        run: swift build -v

      - name: Run tests
        run: swift test -v
